### ISSUE TITLE
how to use this?

### ISSUE THREAD

**Issue by xmljson** [SomeoneSimple/LG-R100-VR-360-Reshade#1]
how to use this?

**Comment by SomeoneSimple** [comment]
It's a filter for Reshade: a post-processing injector for DirectX9~12/OpenGL applications and games.

So to get this working, you will need to install Reshade ( https://reshade.me/ ), start the application/game and in the Reshade UI (it should show up on top if its correctly installed), under settings, point the "Effect Search Paths" to a directory where you downloaded these .fx files on your disk and then enable them.

Mind that some video-players will only allow you to interact with the reshade interface when a video is playing (not pauzed).

For more info on using Reshade you can check [Reshade's FAQ](https://reshade.me/forum/troubleshooting/5227) or one of the many video's on e.g. Youtube.
